import SwiftUI
import CoreML
import Photos
import WebKit

// MARK: - WebGL Boundary Manager

/// Boundary manager for WebGL Gaussian splat rendering
/// Calculates optimal camera positions based on room dimensions
struct WebGLBoundaryManager {
    let width: Float
    let height: Float
    let depth: Float

    /// Default room dimensions when bounds not provided
    static let defaultBounds = WebGLBoundaryManager(width: 4.0, height: 3.0, depth: 2.0)

    init(width: Float, height: Float, depth: Float) {
        self.width = width
        self.height = height
        self.depth = depth
    }

    init(bounds: SIMD3<Float>?) {
        if let b = bounds {
            self.width = b.x
            self.height = b.y
            self.depth = b.z
        } else {
            self = Self.defaultBounds
        }
    }

    /// Calculate optimal camera position for viewing the front wall
    /// Camera positioned to frame the front wall nicely
    /// Returns (eye position, target position) for lookAt camera
    func getOptimalCameraPosition() -> (eye: SIMD3<Float>, target: SIMD3<Float>) {
        // Classic PLY transform: (x, -y, -z)
        // Room extends into negative Z (front wall around -1.4, back wall around -4.7)

        // Front wall is at the "closest" Z (least negative)
        let frontWallZ: Float = -1.4  // Typical front wall position from logs

        // Calculate distance to fit the larger of width/height in view
        // FOV is 60 degrees, so tan(30°) = 0.577
        let maxDim = max(width, height)
        let tanHalfFov: Float = 0.577  // tan(30°)
        var distance = (maxDim / 2) / tanHalfFov

        // Make it tighter (0.6x = 60% of the "fit exactly" distance)
        distance *= 0.6

        let eye = SIMD3<Float>(
            0,                          // Center X
            0,                          // Center Y
            frontWallZ + distance       // In front of the wall
        )

        let target = SIMD3<Float>(
            0,                          // Center X
            0,                          // Center Y
            frontWallZ                  // Look at front wall
        )

        return (eye: eye, target: target)
    }

    /// Get room center point
    var roomCenter: SIMD3<Float> {
        SIMD3<Float>(0, 0, 0)  // Classic PLY is centered at origin
    }

    /// Get room dimensions
    var dimensions: SIMD3<Float> {
        SIMD3<Float>(width, height, depth)
    }
}

/// Simple 3D Gaussian Splat viewer using WebGL (antimatter15/splat)
/// Renders PLY files generated by SHARP
struct SharpRoomView: View {
    let plyURL: URL
    let roomMeasurements: RoomMeasurements?  // Room measurements for display
    let allowSave: Bool  // Show save button (true for new rooms, false for viewing from home)
    let photoOrientation: PhotoOrientation  // Source photo orientation (for UI layout)
    @Environment(\.dismiss) private var dismiss

    // Parsed bounds from PLY file (used when roomMeasurements is nil)
    private let parsedBounds: RoomBounds?

    // Convenience initializer for backwards compatibility
    init(plyURL: URL, roomMeasurements: RoomMeasurements? = nil, allowSave: Bool = true, photoOrientation: PhotoOrientation = .portrait) {
        self.plyURL = plyURL
        self.roomMeasurements = roomMeasurements
        self.allowSave = allowSave
        self.photoOrientation = photoOrientation

        // Compute classic PLY URL (matches what we display and save)
        let classicPath = plyURL.path.replacingOccurrences(of: ".ply", with: "_classic.ply")
        let classicURL = FileManager.default.fileExists(atPath: classicPath)
            ? URL(fileURLWithPath: classicPath)
            : plyURL

        // Always parse bounds from the classic PLY we're displaying
        // This ensures consistent camera framing regardless of whether roomMeasurements is provided
        self.parsedBounds = Self.parsePLYBounds(from: classicURL)
    }

    /// Parse PLY file to extract position bounds (for HomeView where roomMeasurements isn't available)
    private static func parsePLYBounds(from url: URL) -> RoomBounds? {
        guard let data = try? Data(contentsOf: url) else {
            logDebug("PLY Parser: Failed to read file")
            return nil
        }

        // Find end_header
        guard let headerEndRange = data.range(of: Data("end_header\n".utf8)) else {
            logDebug("PLY Parser: No end_header found")
            return nil
        }

        // Parse header for vertex count
        guard let headerString = String(data: data[..<headerEndRange.lowerBound], encoding: .utf8) else {
            logDebug("PLY Parser: Failed to parse header")
            return nil
        }

        var vertexCount = 0
        for line in headerString.components(separatedBy: "\n") {
            if line.hasPrefix("element vertex ") {
                let parts = line.components(separatedBy: " ")
                if parts.count >= 3, let count = Int(parts[2]) {
                    vertexCount = count
                }
            }
        }

        guard vertexCount > 0 else {
            logDebug("PLY Parser: No vertices found")
            return nil
        }

        logDebug("PLY Parser: Found \(vertexCount) vertices")

        // Binary data starts after header
        let binaryStart = headerEndRange.upperBound

        // Each vertex: x,y,z (3 floats) + other properties
        // Stride: 3 floats (xyz) + 3 floats (scale) + 4 floats (rot) + 1 float (opacity) + 3 bytes (rgb) = 47 bytes
        let bytesPerVertex = 47
        let binaryDataLength = data.count - binaryStart

        var minX: Float = .greatestFiniteMagnitude
        var maxX: Float = -.greatestFiniteMagnitude
        var minY: Float = .greatestFiniteMagnitude
        var maxY: Float = -.greatestFiniteMagnitude
        var minZ: Float = .greatestFiniteMagnitude
        var maxZ: Float = -.greatestFiniteMagnitude

        let maxVertices = min(vertexCount, binaryDataLength / bytesPerVertex)

        // Use safe byte copying to avoid alignment issues
        for i in 0..<maxVertices {
            let byteOffset = binaryStart + i * bytesPerVertex
            guard byteOffset + 12 <= data.count else { continue }

            var x: Float = 0
            var y: Float = 0
            var z: Float = 0

            _ = withUnsafeMutableBytes(of: &x) { dest in
                data.copyBytes(to: dest, from: byteOffset..<(byteOffset + 4))
            }
            _ = withUnsafeMutableBytes(of: &y) { dest in
                data.copyBytes(to: dest, from: (byteOffset + 4)..<(byteOffset + 8))
            }
            _ = withUnsafeMutableBytes(of: &z) { dest in
                data.copyBytes(to: dest, from: (byteOffset + 8)..<(byteOffset + 12))
            }

            minX = min(minX, x)
            maxX = max(maxX, x)
            minY = min(minY, y)
            maxY = max(maxY, y)
            minZ = min(minZ, z)
            maxZ = max(maxZ, z)
        }

        guard minX < maxX else {
            logDebug("PLY Parser: Invalid bounds")
            return nil
        }

        logDebug("PLY Parser: Bounds X[\(minX), \(maxX)] Y[\(minY), \(maxY)] Z[\(minZ), \(maxZ)]")

        return RoomBounds(
            minX: minX, maxX: maxX,
            minY: minY, maxY: maxY,
            minZ: minZ, maxZ: maxZ
        )
    }

    /// Get effective bounds - always use parsed bounds from the displayed PLY file
    /// (roomMeasurements.actualBounds uses different coordinate system)
    private var effectiveBounds: RoomBounds? {
        parsedBounds
    }

    @State private var isLoading = true
    @State private var error: String?
    @State private var showingSmartyPants = false
    @State private var capturedImage: UIImage? = nil
    @State private var roomSnapshot: UIImage? = nil
    @State private var mlModel: MLModel? = nil

    // JS-measured front wall dimensions (from actual splat bounds)
    @State private var jsFrontWallWidth: Float?
    @State private var jsFrontWallHeight: Float?

    // Save room state
    @StateObject private var modelManager = USDZModelManager()
    @State private var isSavingRoom = false
    @State private var saveProgress: Double = 0.0
    @State private var savingTimer: Timer?
    @State private var showSaveAlert = false
    @State private var saveAlertMessage = ""
    @State private var saveWasSuccessful = false
    @State private var showRoomNameInput = false
    @State private var roomName = ""
    @State private var showShareSheet = false

    /// Compute classic PLY URL (pre-rotated for antimatter15/splat)
    private var classicPlyURL: URL {
        let path = plyURL.path
        let classicPath = path.replacingOccurrences(of: ".ply", with: "_classic.ply")
        let classicURL = URL(fileURLWithPath: classicPath)
        if FileManager.default.fileExists(atPath: classicPath) {
            return classicURL
        }
        return plyURL
    }

    /// Compute 3DGS PLY URL (SuperSplat compatible format)
    private var threeDGSPlyURL: URL {
        let path = plyURL.path
        let threeDGSPath = path.replacingOccurrences(of: ".ply", with: "_3dgs.ply")
        let threeDGSURL = URL(fileURLWithPath: threeDGSPath)
        if FileManager.default.fileExists(atPath: threeDGSPath) {
            return threeDGSURL
        }
        return plyURL
    }

    var body: some View {
        ZStack {
            // WebGL view using SparkJS (with classic PLY for correct coordinate system)
            AntimatterSplatView(
                plyURL: classicPlyURL,
                roomBounds: roomMeasurements?.boundingBox,
                actualBounds: effectiveBounds,
                onLoaded: {
                    isLoading = false
                },
                onFrontWallDimensions: { w, h in
                    // Store JS-measured dimensions for nav title
                    jsFrontWallWidth = Float(w)
                    jsFrontWallHeight = Float(h)
                }
            )
            .ignoresSafeArea()
            // Prevent swipe-back gesture from interfering with 3D touch controls
            .contentShape(Rectangle())
            .highPriorityGesture(DragGesture(minimumDistance: 0))

            // Loading overlay
            if isLoading {
                VStack(spacing: 16) {
                    ProgressView()
                        .scaleEffect(1.5)
                        .tint(.white)

                    Text("Loading 3D room...")
                        .font(.subheadline)
                        .foregroundColor(.white)
                }
                .padding(24)
                .background(Color.black.opacity(0.7))
                .cornerRadius(12)
            }

            // Error overlay
            if let error = error {
                VStack(spacing: 16) {
                    Image(systemName: "exclamationmark.triangle")
                        .font(.largeTitle)
                        .foregroundColor(.orange)
                    Text(error)
                        .foregroundColor(.white)
                        .multilineTextAlignment(.center)
                }
                .padding(24)
                .background(Color.black.opacity(0.7))
                .cornerRadius(12)
            }

            // SmartyPants overlay (when active) - full screen
            if showingSmartyPants {
                SmartyPantsUIView(
                    capturedImage: $capturedImage,
                    roomImage: roomSnapshot,
                    mlModel: mlModel,
                    processInterval: 0.07,
                    active: true
                )
                .ignoresSafeArea()
                .zIndex(100)
            }


            // Save progress overlay
            if isSavingRoom {
                saveRoomProgressOverlay
            }

            // Landscape layout: controls on LEFT edge (appears at bottom when phone held horizontally)
            // Rotated 90° CW so icons appear upright when phone is horizontal
            if photoOrientation == .landscape {
                // Far left edge controls for landscape - rotated 90° clockwise
                HStack(spacing: 0) {
                    VStack(spacing: 0) {
                        // Brain button (top = left when horizontal)
                        Button(action: {
                            if showingSmartyPants {
                                showingSmartyPants = false
                            } else {
                                NotificationCenter.default.post(name: NSNotification.Name("CaptureMetalSnapshot"), object: nil)
                                DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                                    showingSmartyPants = true
                                }
                            }
                        }) {
                            Image(systemName: "brain.head.profile")
                                .font(.system(size: 28))
                                .foregroundColor(.white)
                                .frame(width: 60, height: 60)
                                .background(Circle().fill(showingSmartyPants ? Color.green : Color.blue).shadow(radius: 5))
                                .rotationEffect(.degrees(90))  // Rotate icon for horizontal viewing
                        }
                        .disabled(isLoading)
                        .padding(.top, 80)

                        Spacer()

                        // Joystick (center) - rotated 90° for horizontal viewing
                        if !showingSmartyPants {
                            JoystickControl()
                                .rotationEffect(.degrees(90))
                        }

                        Spacer()

                        // Screenshot button (bottom = right when horizontal)
                        Button(action: {
                            takeScreenshot()
                        }) {
                            Image(systemName: "camera.fill")
                                .font(.system(size: 28))
                                .foregroundColor(.white)
                                .frame(width: 60, height: 60)
                                .background(Circle().fill(Color.blue).shadow(radius: 5))
                                .rotationEffect(.degrees(90))  // Rotate icon for horizontal viewing
                        }
                        .disabled(isLoading)
                        .padding(.bottom, 30)
                    }
                    .frame(width: 130)  // Fixed width column at left edge
                    .padding(.leading, 0)  // No padding - stick to left edge
                    Spacer()
                }
                .zIndex(99997)
            } else {
                // Portrait layout: standard bottom controls

                // Joystick at bottom center
                if !showingSmartyPants {
                    WebGLJoystickOverlay()
                        .zIndex(99997)
                }

                // Buttons at bottom row
                VStack {
                    Spacer()
                    HStack {
                        // Brain button (bottom-left)
                        Button(action: {
                            if showingSmartyPants {
                                showingSmartyPants = false
                            } else {
                                NotificationCenter.default.post(name: NSNotification.Name("CaptureMetalSnapshot"), object: nil)
                                DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                                    showingSmartyPants = true
                                }
                            }
                        }) {
                            Image(systemName: "brain.head.profile")
                                .font(.system(size: 28))
                                .foregroundColor(.white)
                                .frame(width: 60, height: 60)
                                .background(Circle().fill(showingSmartyPants ? Color.green : Color.blue).shadow(radius: 5))
                        }
                        .disabled(isLoading)
                        .padding(.leading, 16)

                        Spacer()

                        // Screenshot button (bottom-right)
                        Button(action: {
                            takeScreenshot()
                        }) {
                            Image(systemName: "camera.fill")
                                .font(.system(size: 28))
                                .foregroundColor(.white)
                                .frame(width: 60, height: 60)
                                .background(Circle().fill(Color.blue).shadow(radius: 5))
                        }
                        .disabled(isLoading)
                        .padding(.trailing, 16)
                    }
                    .padding(.bottom, 20)
                }
                .zIndex(201)
            }
        }
        .background(Color.black)
        .navigationTitle(navigationTitleWithDimensions)
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            ToolbarItemGroup(placement: .navigationBarTrailing) {
                // Share button - only in debug mode
                if AppStateManager.shared.qualitySettings.debugMode {
                    Button(action: {
                        showShareSheet = true
                    }) {
                        Image(systemName: "square.and.arrow.up")
                    }
                    .disabled(isLoading)
                }

                // Save button (only for new rooms, not when viewing from home)
                if allowSave {
                    Button(action: {
                        showRoomNameInput = true
                    }) {
                        Image(systemName: "square.and.arrow.down")
                    }
                    .disabled(isLoading)
                }

                // Recenter button
                Button(action: {
                    NotificationCenter.default.post(name: NSNotification.Name("RecenterWebGLCamera"), object: nil)
                }) {
                    Image(systemName: "viewfinder")
                }
                .disabled(isLoading)
            }
        }
        .sheet(isPresented: $showShareSheet) {
            // Share the 3DGS format (SuperSplat compatible)
            ShareSheet(activityItems: [threeDGSPlyURL])
        }
        .onAppear {
            loadMLModel()
            // Lock to portrait orientation for 3D view stability
            OrientationLockManager.shared.lockToPortrait()
        }
        .onDisappear {
            // Unlock orientation when leaving the view
            OrientationLockManager.shared.unlock()
        }
        // Room name input alert
        .alert("Save Room", isPresented: $showRoomNameInput) {
            TextField("Room name", text: $roomName)
            Button("Cancel", role: .cancel) {
                roomName = ""
            }
            Button("Save") {
                startSavingRoom()
            }
            .disabled(roomName.isEmpty)
        } message: {
            Text("Enter a name for this room")
        }
        // Save result alert
        .alert("Room Save", isPresented: $showSaveAlert) {
            Button("OK", role: .cancel) {
                if saveWasSuccessful {
                    // Dismiss entire sheet and go back to home view
                    NotificationCenter.default.post(name: NSNotification.Name("DismissPhotoRoomSheet"), object: nil)
                }
            }
        } message: {
            Text(saveAlertMessage)
        }
    }

    // MARK: - Screenshot

    private func takeScreenshot() {
        logDebug("📸 Taking screenshot...")

        // Capture the window
        let scenes = UIApplication.shared.connectedScenes.compactMap { $0 as? UIWindowScene }
        let windows = scenes.flatMap { $0.windows }
        guard let window = windows.first(where: { $0.isKeyWindow }) ?? windows.first else {
            logDebug("❌ No window found")
            return
        }

        let format = UIGraphicsImageRendererFormat()
        format.scale = UIScreen.main.scale
        let renderer = UIGraphicsImageRenderer(bounds: window.bounds, format: format)
        let image = renderer.image { _ in
            window.drawHierarchy(in: window.bounds, afterScreenUpdates: true)
        }

        logDebug("📸 Screenshot captured, saving to Photos...")

        // Save to photos
        UIImageWriteToSavedPhotosAlbum(image, nil, nil, nil)
        logDebug("✅ Screenshot saved to Photos")
    }

    // MARK: - Load ML Model for SmartyPants

    private func loadMLModel() {
        guard mlModel == nil else { return }

        let candidateNames = [
            ("yoloe-11l-seg-pf", "mlmodelc"),
        ]

        for (name, ext) in candidateNames {
            if let url = Bundle.main.url(forResource: name, withExtension: ext) {
                do {
                    let config = MLModelConfiguration()
                    config.computeUnits = .cpuOnly
                    let model = try MLModel(contentsOf: url, configuration: config)
                    self.mlModel = model
                    logDebug("✅ [SharpRoomView] Loaded MLModel '\(name).\(ext)'")
                    break
                } catch {
                    logDebug("❌ [SharpRoomView] Failed to load \(name).\(ext): \(error)")
                }
            }
        }
    }

    // MARK: - Navigation Title with Dimensions
    private var navigationTitleWithDimensions: String {
        // Show front wall dimensions (width × height)
        let wallWidth = roomMeasurements?.frontWallWidth
            ?? jsFrontWallWidth
            ?? 4.0
        let wallHeight = roomMeasurements?.frontWallHeight
            ?? jsFrontWallHeight
            ?? 3.0

        return String(format: "%.1f × %.1f m", wallWidth, wallHeight)
    }

    /// Get file size of the PLY file
    private func getFileSize() -> String {
        let url = classicPlyURL
        guard let attributes = try? FileManager.default.attributesOfItem(atPath: url.path),
              let size = attributes[.size] as? UInt64 else {
            return "Unknown"
        }

        let mb = Double(size) / (1024 * 1024)
        if mb >= 1.0 {
            return String(format: "%.1f MB", mb)
        } else {
            let kb = Double(size) / 1024
            return String(format: "%.0f KB", kb)
        }
    }

    // MARK: - Save Room Progress Overlay
    private var saveRoomProgressOverlay: some View {
        ZStack {
            Color.black.opacity(0.9)
                .ignoresSafeArea()

            VStack(spacing: 24) {
                ZStack {
                    Circle()
                        .fill(Color.green.opacity(0.2))
                        .frame(width: 100, height: 100)

                    Image(systemName: "square.and.arrow.down")
                        .font(.system(size: 40))
                        .foregroundColor(.green)
                }

                Text("Saving Room...")
                    .font(.title2)
                    .fontWeight(.semibold)
                    .foregroundColor(.white)

                ProgressView(value: saveProgress)
                    .progressViewStyle(LinearProgressViewStyle(tint: .green))
                    .frame(width: 200)

                Text("\(Int(saveProgress * 100))%")
                    .font(.headline)
                    .foregroundColor(.gray)

                Button("Cancel") {
                    cancelSavingRoom()
                }
                .foregroundColor(.red)
                .padding(.top, 20)
            }
        }
    }

    // MARK: - Save Room Functions
    private func startSavingRoom() {
        guard !roomName.isEmpty else { return }

        let savedName = roomName
        logDebug("💾 [SharpRoomView] Starting room save: \(savedName)")

        withAnimation(.easeIn(duration: 0.3)) {
            isSavingRoom = true
            saveProgress = 0.0
        }

        var saveStarted = false
        var saveCompleted = false
        var saveSuccess = false
        var saveError: String?

        savingTimer = Timer.scheduledTimer(withTimeInterval: 0.05, repeats: true) { timer in
            if !saveStarted || (saveStarted && saveCompleted) {
                self.saveProgress += 0.015
            }

            if self.saveProgress >= 0.6 && !saveStarted {
                saveStarted = true
                // Save the classic PLY file (pre-transformed for correct viewing)
                self.modelManager.savePLY(from: self.classicPlyURL, name: savedName, photoOrientation: self.photoOrientation) { success, error in
                    DispatchQueue.main.async {
                        saveCompleted = true
                        saveSuccess = success
                        saveError = error
                        logDebug(success ? "✅ [SharpRoomView] Room saved" : "❌ [SharpRoomView] Save failed: \(error ?? "unknown")")
                    }
                }
            }

            if self.saveProgress >= 1.0 && saveCompleted {
                timer.invalidate()
                self.savingTimer = nil

                withAnimation(.easeOut(duration: 0.3)) {
                    self.isSavingRoom = false
                }

                DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                    if saveSuccess {
                        self.saveAlertMessage = "Room '\(savedName)' saved successfully!"
                        self.saveWasSuccessful = true
                    } else {
                        self.saveAlertMessage = "Failed to save: \(saveError ?? "Unknown error")"
                        self.saveWasSuccessful = false
                    }
                    self.showSaveAlert = true
                    self.roomName = ""
                }
            }
        }
    }

    private func cancelSavingRoom() {
        savingTimer?.invalidate()
        savingTimer = nil

        withAnimation(.easeOut(duration: 0.2)) {
            isSavingRoom = false
            saveProgress = 0.0
        }

        roomName = ""
        logDebug("❌ [SharpRoomView] Room save cancelled")
    }

}

// MARK: - Antimatter15 WebGL Splat View

/// Custom URL scheme handler to serve HTML and PLY files to WKWebView
class LocalFileSchemeHandler: NSObject, WKURLSchemeHandler {
    var plyURL: URL?
    var htmlContent: String = ""
    var loadStartTime: CFAbsoluteTime = 0

    func webView(_ webView: WKWebView, start urlSchemeTask: WKURLSchemeTask) {
        guard let requestURL = urlSchemeTask.request.url else {
            urlSchemeTask.didFailWithError(NSError(domain: "LocalFileSchemeHandler", code: -1, userInfo: nil))
            return
        }

        let path = requestURL.path
        logDebug("LocalFileSchemeHandler: Request for \(path)")

        // Serve the HTML page
        if path == "/" || path == "/index.html" || path.isEmpty {
            let data = htmlContent.data(using: .utf8) ?? Data()
            let response = HTTPURLResponse(
                url: requestURL,
                statusCode: 200,
                httpVersion: "HTTP/1.1",
                headerFields: [
                    "Content-Type": "text/html; charset=utf-8",
                    "Content-Length": "\(data.count)"
                ]
            )!
            urlSchemeTask.didReceive(response)
            urlSchemeTask.didReceive(data)
            urlSchemeTask.didFinish()
            logDebug("LocalFileSchemeHandler: Served HTML (\(data.count) bytes)")
            return
        }

        // Serve the PLY file
        if path == "/room.ply", let plyURL = plyURL {
            do {
                let readStart = CFAbsoluteTimeGetCurrent()
                let data = try Data(contentsOf: plyURL)
                let readTime = (CFAbsoluteTimeGetCurrent() - readStart) * 1000

                let response = HTTPURLResponse(
                    url: requestURL,
                    statusCode: 200,
                    httpVersion: "HTTP/1.1",
                    headerFields: [
                        "Content-Type": "application/octet-stream",
                        "Content-Length": "\(data.count)",
                        "Access-Control-Allow-Origin": "*"
                    ]
                )!
                urlSchemeTask.didReceive(response)
                urlSchemeTask.didReceive(data)
                urlSchemeTask.didFinish()

                let sizeMB = Double(data.count) / (1024 * 1024)
                logDebug("⏱️ [WebGL] PLY file read: \(String(format: "%.0f", readTime))ms (\(String(format: "%.1f", sizeMB)) MB)")
            } catch {
                logDebug("LocalFileSchemeHandler: Failed to read PLY: \(error)")
                urlSchemeTask.didFailWithError(error)
            }
            return
        }

        // Serve the local main.js (modified antimatter15/splat)
        if path == "/main.js" {
            // Try bundle first
            if let jsURL = Bundle.main.url(forResource: "splat_main", withExtension: "js"),
               let data = try? Data(contentsOf: jsURL) {
                let response = HTTPURLResponse(
                    url: requestURL,
                    statusCode: 200,
                    httpVersion: "HTTP/1.1",
                    headerFields: [
                        "Content-Type": "application/javascript; charset=utf-8",
                        "Content-Length": "\(data.count)"
                    ]
                )!
                urlSchemeTask.didReceive(response)
                urlSchemeTask.didReceive(data)
                urlSchemeTask.didFinish()
                logDebug("LocalFileSchemeHandler: Served main.js from bundle (\(data.count) bytes)")
                return
            }

            // Try filesystem path as fallback
            let fsPath = "/Users/al/Documents/tries01/Furnit/Furnit/Resources/splat_main.js"
            if let data = try? Data(contentsOf: URL(fileURLWithPath: fsPath)) {
                let response = HTTPURLResponse(
                    url: requestURL,
                    statusCode: 200,
                    httpVersion: "HTTP/1.1",
                    headerFields: [
                        "Content-Type": "application/javascript; charset=utf-8",
                        "Content-Length": "\(data.count)"
                    ]
                )!
                urlSchemeTask.didReceive(response)
                urlSchemeTask.didReceive(data)
                urlSchemeTask.didFinish()
                logDebug("LocalFileSchemeHandler: Served main.js from filesystem (\(data.count) bytes)")
                return
            }

            logDebug("LocalFileSchemeHandler: main.js not found anywhere!")
        }

        // 404 for other paths
        let errorResponse = HTTPURLResponse(
            url: requestURL,
            statusCode: 404,
            httpVersion: "HTTP/1.1",
            headerFields: nil
        )!
        urlSchemeTask.didReceive(errorResponse)
        urlSchemeTask.didReceive(Data())
        urlSchemeTask.didFinish()
    }

    func webView(_ webView: WKWebView, stop urlSchemeTask: WKURLSchemeTask) {
        // Nothing to clean up
    }
}

/// WebGL-based 3D Gaussian Splat viewer using antimatter15/splat
/// Renders PLY files in a WKWebView using WebGL
struct AntimatterSplatView: UIViewRepresentable {
    let plyURL: URL
    let roomBounds: SIMD3<Float>?  // Room dimensions for camera positioning
    let actualBounds: RoomBounds?  // Actual min/max bounds for precise framing
    let onLoaded: () -> Void
    var onFrontWallDimensions: ((Double, Double) -> Void)? = nil

    func makeCoordinator() -> Coordinator {
        Coordinator(onLoaded: onLoaded, onFrontWallDimensions: onFrontWallDimensions)
    }

    func makeUIView(context: Context) -> WKWebView {
        let config = WKWebViewConfiguration()
        config.allowsInlineMediaPlayback = true

        // Enable JavaScript
        let prefs = WKWebpagePreferences()
        prefs.allowsContentJavaScript = true
        config.defaultWebpagePreferences = prefs

        // Register custom URL scheme handler
        let schemeHandler = LocalFileSchemeHandler()
        schemeHandler.plyURL = plyURL
        schemeHandler.htmlContent = generateSplatViewerHTML(bounds: roomBounds, actualBounds: actualBounds)
        config.setURLSchemeHandler(schemeHandler, forURLScheme: "splat")

        // Add message handlers for communication from JS
        config.userContentController.add(context.coordinator, name: "splatLoaded")
        config.userContentController.add(context.coordinator, name: "frontWallDimensions")

        let webView = WKWebView(frame: .zero, configuration: config)
        webView.navigationDelegate = context.coordinator
        webView.scrollView.isScrollEnabled = false
        webView.isOpaque = false
        webView.backgroundColor = .black

        // Store reference
        context.coordinator.schemeHandler = schemeHandler
        context.coordinator.webView = webView

        // Load from custom scheme (HTML will auto-load room.ply)
        if let url = URL(string: "splat://local/") {
            webView.load(URLRequest(url: url))
            logDebug("AntimatterSplatView: Loading from custom scheme")
        }

        return webView
    }

    func updateUIView(_ uiView: WKWebView, context: Context) {
        // No updates needed
    }

    private func generateSplatViewerHTML(bounds: SIMD3<Float>?, actualBounds: RoomBounds?) -> String {
        // Use boundary manager to calculate camera position
        let boundaryManager = WebGLBoundaryManager(bounds: bounds)
        let cameraSetup = boundaryManager.getOptimalCameraPosition()

        let eyeX = cameraSetup.eye.x
        let eyeY = cameraSetup.eye.y
        let eyeZ = cameraSetup.eye.z

        let targetX = cameraSetup.target.x
        let targetY = cameraSetup.target.y
        let targetZ = cameraSetup.target.z

        logDebug("📐 [WebGL] Room bounds: \(boundaryManager.width) × \(boundaryManager.height) × \(boundaryManager.depth)")
        logDebug("📷 [WebGL] Camera: eye=(\(eyeX), \(eyeY), \(eyeZ)) target=(\(targetX), \(targetY), \(targetZ))")

        // Debug actual bounds
        if let ab = actualBounds {
            logDebug("📏 [WebGL] Actual bounds: X[\(ab.minX), \(ab.maxX)] Y[\(ab.minY), \(ab.maxY)] Z[\(ab.minZ), \(ab.maxZ)]")
            logDebug("📏 [WebGL] Front wall at Z=\(ab.frontZ), center=(\(ab.centerX), \(ab.centerY))")
        } else {
            logDebug("⚠️ [WebGL] No actual bounds available - will use Box3 fallback")
        }

        // SparkJS + THREE.js based Gaussian Splat viewer
        return """
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
            <title>3D Room</title>
            <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                html, body {
                    width: 100%;
                    height: 100%;
                    overflow: hidden;
                    background: #1a1a1a;
                    touch-action: none;
                    -webkit-touch-callout: none;
                    -webkit-user-select: none;
                }
                canvas {
                    width: 100%;
                    height: 100%;
                    display: block;
                    touch-action: none;
                }
            </style>
            <script type="importmap">
            {
                "imports": {
                    "three": "https://cdnjs.cloudflare.com/ajax/libs/three.js/0.170.0/three.module.min.js",
                    "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/",
                    "@sparkjsdev/spark": "https://sparkjs.dev/releases/spark/0.1.10/spark.module.js"
                }
            }
            </script>
        </head>
        <body>
            <script type="module">
                import * as THREE from 'three';
                import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
                import { SplatMesh, SparkRenderer } from '@sparkjsdev/spark';

                // Log JS errors
                window.addEventListener('error', function(e) {
                    console.log('[JS Error] ' + e.message + ' at ' + e.filename + ':' + e.lineno);
                });

                const jsStartTime = performance.now();

                // Scene setup
                const scene = new THREE.Scene();
                scene.background = new THREE.Color(0x1a1a1a);

                // Camera - position to see room
                const camera = new THREE.PerspectiveCamera(60, window.innerWidth / window.innerHeight, 0.1, 1000);
                camera.position.set(0, 0, 5);
                camera.up.set(-1, 0, 0);  // Rotate view 90° CCW to fix left tilt from PLY

                // THREE.js Renderer (for SparkRenderer)
                const renderer = new THREE.WebGLRenderer({ antialias: false });  // antialias: false per SparkJS docs
                renderer.setSize(window.innerWidth, window.innerHeight);
                renderer.setPixelRatio(window.devicePixelRatio);
                document.body.appendChild(renderer.domElement);

                // SparkRenderer for Gaussian-specific rendering (sharper preset)
                const spark = new SparkRenderer({
                    renderer: renderer,
                    maxStdDev: Math.sqrt(6),    // Tighter Gaussians (default is sqrt(8))
                    preBlurAmount: 0.0,         // No pre-blur smearing
                    blurAmount: 0.2,            // Minimal post blur
                    falloff: 1.0,               // Normal Gaussian kernel
                    focalAdjustment: 2.0        // Extra sharpness per docs
                });
                camera.add(spark);  // Add SparkRenderer as child of camera

                // Orbit controls for touch/mouse
                const controls = new OrbitControls(camera, renderer.domElement);
                controls.enableDamping = true;
                controls.dampingFactor = 0.05;
                controls.screenSpacePanning = false;
                controls.minDistance = 0.4;   // Allow closer zooming
                controls.maxDistance = 20;
                controls.target.set(0, 0, 0);

                // Save initial camera state for recenter (will be updated after auto-frame)
                let initialCameraPosition = camera.position.clone();
                let initialControlsTarget = controls.target.clone();

                // Recenter function
                window.recenterCamera = function() {
                    camera.position.copy(initialCameraPosition);
                    controls.target.copy(initialControlsTarget);
                    controls.update();
                };

                // Function to update initial position (called after auto-frame)
                window.updateInitialPosition = function() {
                    initialCameraPosition = camera.position.clone();
                    initialControlsTarget = controls.target.clone();
                    console.log('Updated initial position for recenter:', initialCameraPosition);
                };

                // Load PLY splat using SparkJS
                const plyURL = 'splat://local/room.ply';
                console.log('Loading splat from:', plyURL);

                let splatMesh = null;
                try {
                    splatMesh = new SplatMesh({
                        url: plyURL,
                        maxSh: 0  // Disable spherical harmonics for cleaner look
                    });
                    scene.add(splatMesh);
                    console.log('SplatMesh added to scene');

                    // Auto-frame using actual bounds from Swift
                    console.log('=== AUTO-FRAME SETUP ===');
                    const hasActualBounds = \(actualBounds != nil ? "true" : "false");
                    const swiftBounds = {
                        minX: \(actualBounds?.minX ?? 0),
                        maxX: \(actualBounds?.maxX ?? 0),
                        minY: \(actualBounds?.minY ?? 0),
                        maxY: \(actualBounds?.maxY ?? 0),
                        minZ: \(actualBounds?.minZ ?? 0),
                        maxZ: \(actualBounds?.maxZ ?? 0)
                    };
                    console.log('hasActualBounds:', hasActualBounds);
                    console.log('swiftBounds:', JSON.stringify(swiftBounds));

                    function autoFrameRoom() {
                        console.log('=== autoFrameRoom() called ===');
                        try {
                            let wallWidth, wallHeight, centerX, centerY, frontZ, backZ;

                            if (hasActualBounds && swiftBounds.maxX !== 0) {
                                // Use Swift-computed bounds (accurate)
                                wallWidth = swiftBounds.maxX - swiftBounds.minX;
                                wallHeight = swiftBounds.maxY - swiftBounds.minY;
                                centerX = (swiftBounds.minX + swiftBounds.maxX) / 2;
                                centerY = (swiftBounds.minY + swiftBounds.maxY) / 2;
                                frontZ = swiftBounds.maxZ;
                                backZ = swiftBounds.minZ;
                                console.log('Using Swift bounds');
                            } else {
                                // Fallback: try Box3
                                console.log('No Swift bounds, trying Box3...');
                                const box = new THREE.Box3().setFromObject(splatMesh);
                                const size = box.getSize(new THREE.Vector3());
                                console.log('Box3 size:', size.x, size.y, size.z);
                                if (size.length() < 0.01) {
                                    console.log('Waiting for splat...');
                                    setTimeout(autoFrameRoom, 100);
                                    return;
                                }
                                wallWidth = size.x;
                                wallHeight = size.y;
                                const center = box.getCenter(new THREE.Vector3());
                                centerX = center.x;
                                centerY = center.y;
                                frontZ = box.max.z;
                                backZ = box.min.z;
                            }

                            console.log('Wall:', wallWidth.toFixed(2), 'x', wallHeight.toFixed(2));
                            console.log('Center:', centerX.toFixed(2), centerY.toFixed(2), 'frontZ:', frontZ.toFixed(2));

                            // Store bounds for camera clamping
                            roomBoundsForClamping = {
                                minX: centerX - wallWidth / 2,
                                maxX: centerX + wallWidth / 2,
                                minZ: backZ,
                                maxZ: frontZ
                            };
                            console.log('Camera bounds set:', JSON.stringify(roomBoundsForClamping));

                            // Send to Swift
                            if (window.webkit?.messageHandlers?.frontWallDimensions) {
                                window.webkit.messageHandlers.frontWallDimensions.postMessage({
                                    width: wallWidth, height: wallHeight
                                });
                            }

                            // --- CAMERA IN FRONT OF ROOM, LOOKING AT FRONT WALL ---
                            // SHARP classic PLY: front wall at minZ (most negative), back wall at maxZ

                            // Swap: front wall is actually at minZ (backZ variable), not maxZ
                            const actualFrontZ = backZ;  // minZ = front wall
                            const actualBackZ = frontZ;  // maxZ = back wall

                            const maxDim = Math.max(wallWidth, wallHeight);
                            const fov = THREE.MathUtils.degToRad(camera.fov);
                            const aspect = window.innerWidth / window.innerHeight;

                            // Distance needed so the wall fits in vertical & horizontal FOV
                            const fitHeightDist = (maxDim * 0.5) / Math.tan(fov * 0.5);
                            const fitWidthDist  = (maxDim * 0.5) / (Math.tan(fov * 0.5) * aspect);
                            let distance = Math.max(fitHeightDist, fitWidthDist);
                            distance *= 1.05;  // Small padding so wall isn't touching edges

                            // Camera positioned in front of front wall (actualFrontZ - distance)
                            const newCamPos = new THREE.Vector3(
                                centerX,                    // Center X
                                centerY,                    // Center Y (middle height)
                                actualFrontZ - distance     // In front of front wall (more negative)
                            );

                            // Look at middle of front wall
                            const newTarget = new THREE.Vector3(
                                centerX,                // Center X
                                centerY,                // Center Y
                                actualFrontZ            // Front wall (minZ)
                            );

                            console.log('Auto-framed front wall:',
                                'wallWidth=', wallWidth.toFixed(2),
                                'wallHeight=', wallHeight.toFixed(2),
                                'actualFrontZ=', actualFrontZ.toFixed(2),
                                'distance=', distance.toFixed(2)
                            );

                            console.log('OLD camera pos:', camera.position.x.toFixed(2), camera.position.y.toFixed(2), camera.position.z.toFixed(2));
                            console.log('NEW camera pos:', newCamPos.x.toFixed(2), newCamPos.y.toFixed(2), newCamPos.z.toFixed(2));
                            console.log('NEW target:', newTarget.x.toFixed(2), newTarget.y.toFixed(2), newTarget.z.toFixed(2));

                            camera.position.copy(newCamPos);
                            controls.target.copy(newTarget);
                            controls.update();

                            // Update initial recenter state to this auto-framed position
                            initialCameraPosition.copy(camera.position);
                            initialControlsTarget.copy(controls.target);

                            console.log('=== Camera MOVED & recenter updated ===');
                        } catch (err) {
                            console.error('autoFrameRoom error:', err);
                        }
                    }
                    console.log('Scheduling autoFrameRoom in 500ms...');
                    setTimeout(autoFrameRoom, 500);

                } catch (err) {
                    console.error('Failed to load splat:', err);
                }

                // Handle resize
                window.addEventListener('resize', () => {
                    camera.aspect = window.innerWidth / window.innerHeight;
                    camera.updateProjectionMatrix();
                    renderer.setSize(window.innerWidth, window.innerHeight);
                });

                // Room bounds for camera clamping (will be set by autoFrameRoom)
                let roomBoundsForClamping = null;

                // Joystick movement handler with boundary clamping
                window.moveCamera = function(dx, dy) {
                    const moveSpeed = 0.015;  // Reduced sensitivity

                    // Calculate new position
                    let newX = camera.position.x + dx * moveSpeed;
                    let newZ = camera.position.z + dy * moveSpeed;

                    // Clamp to room bounds if available
                    if (roomBoundsForClamping) {
                        const margin = 0.5;  // Small margin inside bounds
                        newX = Math.max(roomBoundsForClamping.minX + margin,
                               Math.min(roomBoundsForClamping.maxX - margin, newX));
                        newZ = Math.max(roomBoundsForClamping.minZ + margin,
                               Math.min(roomBoundsForClamping.maxZ - margin, newZ));
                    }

                    // Apply clamped movement
                    const actualDx = newX - camera.position.x;
                    const actualDz = newZ - camera.position.z;

                    camera.position.x = newX;
                    camera.position.z = newZ;
                    controls.target.x += actualDx;
                    controls.target.z += actualDz;
                };

                // Animation loop
                let loadNotified = false;
                function animate() {
                    requestAnimationFrame(animate);
                    controls.update();

                    // Use SparkRenderer's update method for optimized Gaussian rendering
                    spark.update({ scene });
                    renderer.render(scene, camera);

                    // Notify Swift when loaded
                    if (!loadNotified && splatMesh) {
                        loadNotified = true;
                        const totalTime = performance.now() - jsStartTime;
                        if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.splatLoaded) {
                            window.webkit.messageHandlers.splatLoaded.postMessage({ loaded: true, timeMs: totalTime });
                        }
                        console.log('Splat loaded in', totalTime, 'ms');
                    }
                }
                animate();
            </script>
        </body>
        </html>
        """
    }

    class Coordinator: NSObject, WKNavigationDelegate, WKScriptMessageHandler {
        var webView: WKWebView?
        var schemeHandler: LocalFileSchemeHandler?
        let onLoaded: () -> Void
        let onFrontWallDimensions: ((Double, Double) -> Void)?
        private var hasNotifiedLoaded = false
        private var loadStartTime: CFAbsoluteTime = 0

        private var joystickTimer: Timer?

        init(onLoaded: @escaping () -> Void, onFrontWallDimensions: ((Double, Double) -> Void)? = nil) {
            self.onLoaded = onLoaded
            self.onFrontWallDimensions = onFrontWallDimensions
            self.loadStartTime = CFAbsoluteTimeGetCurrent()
            logDebug("⏱️ [WebGL] Starting load...")
            super.init()

            // Listen for recenter notification
            NotificationCenter.default.addObserver(
                self,
                selector: #selector(recenterCamera),
                name: NSNotification.Name("RecenterWebGLCamera"),
                object: nil
            )

            // Listen for joystick movement
            NotificationCenter.default.addObserver(
                self,
                selector: #selector(handleJoystickMove(_:)),
                name: NSNotification.Name("WebGLJoystickMove"),
                object: nil
            )
        }

        deinit {
            joystickTimer?.invalidate()
            NotificationCenter.default.removeObserver(self)
        }

        @objc private func recenterCamera() {
            logDebug("🎯 [WebGL] Recentering camera")
            let js = "if (typeof recenterCamera === 'function') recenterCamera();"
            webView?.evaluateJavaScript(js) { _, error in
                if let error = error {
                    logDebug("❌ [WebGL] Recenter JS error: \(error)")
                }
            }
        }

        @objc private func handleJoystickMove(_ notification: Notification) {
            guard let userInfo = notification.userInfo,
                  let offset = userInfo["offset"] as? CGSize else { return }

            let dx = Float(offset.width)
            let dy = Float(-offset.height)  // Invert Y for intuitive control

            // Skip if no movement
            if abs(dx) < 0.01 && abs(dy) < 0.01 { return }

            // Call SparkJS moveCamera function
            let js = "if (typeof moveCamera === 'function') moveCamera(\(dx), \(dy));"
            webView?.evaluateJavaScript(js, completionHandler: nil)
        }

        func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
            let elapsed = (CFAbsoluteTimeGetCurrent() - loadStartTime) * 1000
            logDebug("⏱️ [WebGL] HTML page loaded: \(String(format: "%.0f", elapsed))ms")

            // Fallback: notify loaded after delay if JS doesn't report
            DispatchQueue.main.asyncAfter(deadline: .now() + 5.0) {
                if !self.hasNotifiedLoaded {
                    self.hasNotifiedLoaded = true
                    let total = (CFAbsoluteTimeGetCurrent() - self.loadStartTime) * 1000
                    logDebug("⏱️ [WebGL] Total load (fallback): \(String(format: "%.0f", total))ms")
                    self.onLoaded()
                }
            }
        }

        func webView(_ webView: WKWebView, didFail navigation: WKNavigation!, withError error: Error) {
            logDebug("❌ [WebGL] Navigation failed: \(error)")
        }

        func webView(_ webView: WKWebView, didFailProvisionalNavigation navigation: WKNavigation!, withError error: Error) {
            logDebug("❌ [WebGL] Provisional navigation failed: \(error)")
        }

        func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {
            if message.name == "splatLoaded" {
                if let body = message.body as? [String: Any], body["loaded"] != nil {
                    let elapsed = (CFAbsoluteTimeGetCurrent() - loadStartTime) * 1000
                    logDebug("⏱️ [WebGL] Splat rendered: \(String(format: "%.0f", elapsed))ms total")

                    if !hasNotifiedLoaded {
                        hasNotifiedLoaded = true
                        DispatchQueue.main.async {
                            self.onLoaded()
                        }
                    }
                }
            } else if message.name == "frontWallDimensions" {
                if let body = message.body as? [String: Any],
                   let w = body["width"] as? Double,
                   let h = body["height"] as? Double {
                    logDebug("📏 [WebGL] Front wall from JS: \(String(format: "%.2f", w)) × \(String(format: "%.2f", h))")
                    DispatchQueue.main.async {
                        self.onFrontWallDimensions?(w, h)
                    }
                }
            }
        }
    }
}

// MARK: - WebGL Joystick Control

/// Just the joystick control without positioning (for use in custom layouts)
struct JoystickControl: View {
    @State private var offset: CGSize = .zero
    @State private var isDragging = false

    private let joystickSize: CGFloat = 120
    private let knobSize: CGFloat = 50
    private let maxOffset: CGFloat = 35

    var body: some View {
        ZStack {
            // Outer ring
            Circle()
                .fill(Color.black.opacity(0.3))
                .frame(width: joystickSize, height: joystickSize)

            // Directional indicators
            Circle()
                .stroke(Color.white.opacity(0.3), lineWidth: 2)
                .frame(width: joystickSize - 10, height: joystickSize - 10)

            // Knob
            Circle()
                .fill(isDragging ? Color.blue : Color.white.opacity(0.8))
                .frame(width: knobSize, height: knobSize)
                .shadow(color: .black.opacity(0.3), radius: 4)
                .offset(offset)
        }
        .gesture(
            DragGesture()
                .onChanged { value in
                    isDragging = true
                    let translation = value.translation

                    // Clamp to circular bounds
                    let distance = sqrt(translation.width * translation.width + translation.height * translation.height)
                    if distance > maxOffset {
                        let scale = maxOffset / distance
                        offset = CGSize(
                            width: translation.width * scale,
                            height: translation.height * scale
                        )
                    } else {
                        offset = translation
                    }

                    // Post notification for WebGL camera movement
                    NotificationCenter.default.post(
                        name: NSNotification.Name("WebGLJoystickMove"),
                        object: nil,
                        userInfo: ["offset": offset]
                    )
                }
                .onEnded { _ in
                    isDragging = false
                    withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                        offset = .zero
                    }
                    // Post zero offset to stop movement
                    NotificationCenter.default.post(
                        name: NSNotification.Name("WebGLJoystickMove"),
                        object: nil,
                        userInfo: ["offset": CGSize.zero]
                    )
                }
        )
    }
}

// MARK: - WebGL Joystick Overlay

/// Joystick overlay for portrait mode - positioned at bottom center
struct WebGLJoystickOverlay: View {
    var body: some View {
        VStack {
            Spacer()
            HStack {
                Spacer()
                JoystickControl()
                Spacer()
            }
            .padding(.bottom, 40)
        }
    }
}

// MARK: - Share Sheet

/// UIActivityViewController wrapper for sharing files
struct ShareSheet: UIViewControllerRepresentable {
    let activityItems: [Any]

    func makeUIViewController(context: Context) -> UIActivityViewController {
        let controller = UIActivityViewController(
            activityItems: activityItems,
            applicationActivities: nil
        )
        return controller
    }

    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {}
}

// MARK: - Preview

#Preview {
    NavigationStack {
        // Preview with a sample URL (won't actually load)
        SharpRoomView(plyURL: URL(fileURLWithPath: "/sample.ply"))
    }
}

