import SwiftUI
import MetalKit

// Note: Add MetalSplatter package via Xcode:
// File > Add Package Dependencies > https://github.com/scier/MetalSplatter.git
import MetalSplatter

/// Simple 3D Gaussian Splat viewer using MetalSplatter
/// Renders PLY files generated by SHARP without any room-aware processing
struct SharpRoomView: View {
    let plyURL: URL

    @State private var isLoading = true
    @State private var error: String?
    @State private var splatCount: Int = 0
    @State private var roomWidth: Float = 0
    @State private var roomHeight: Float = 0
    @State private var roomDepth: Float = 0
    @State private var memoryMB: Float = 0
    @State private var isSaving = false

    var body: some View {
        ZStack {
            // MetalSplatter view
            MetalSplatterViewRepresentable(
                plyURL: plyURL,
                onLoaded: { count, width, height, depth, memory in
                    splatCount = count
                    roomWidth = width
                    roomHeight = height
                    roomDepth = depth
                    memoryMB = memory
                    isLoading = false
                },
                onError: { err in
                    error = err
                    isLoading = false
                }
            )
            .ignoresSafeArea()

            // Loading overlay
            if isLoading {
                VStack(spacing: 16) {
                    ProgressView()
                        .scaleEffect(1.5)
                    Text("Loading splats...")
                        .foregroundColor(.white)
                }
                .padding(24)
                .background(Color.black.opacity(0.7))
                .cornerRadius(12)
            }

            // Error overlay
            if let error = error {
                VStack(spacing: 16) {
                    Image(systemName: "exclamationmark.triangle")
                        .font(.largeTitle)
                        .foregroundColor(.orange)
                    Text(error)
                        .foregroundColor(.white)
                        .multilineTextAlignment(.center)
                }
                .padding(24)
                .background(Color.black.opacity(0.7))
                .cornerRadius(12)
            }

            // HUD
            VStack {
                HStack {
                    if splatCount > 0 {
                        VStack(alignment: .leading, spacing: 2) {
                            Text("W: \(String(format: "%.1f", roomWidth))m  H: \(String(format: "%.1f", roomHeight))m  D: \(String(format: "%.1f", roomDepth))m")
                                .font(.caption.monospacedDigit())
                                .foregroundColor(.white)
                            Text("\(String(format: "%.1f", memoryMB)) MB")
                                .font(.caption2.monospacedDigit())
                                .foregroundColor(.white.opacity(0.7))
                        }
                        .padding(8)
                        .background(Color.black.opacity(0.5))
                        .cornerRadius(8)
                    }
                    Spacer()

                    // Recenter button
                    Button(action: {
                        NotificationCenter.default.post(name: NSNotification.Name("RecenterCamera"), object: nil)
                    }) {
                        Image(systemName: "viewfinder")
                            .font(.system(size: 20))
                            .foregroundColor(.white)
                            .frame(width: 44, height: 44)
                            .background(Circle().fill(Color.gray.opacity(0.8)))
                    }
                    .disabled(isLoading)

                    // Save room button
                    Button(action: saveRoom) {
                        Image(systemName: isSaving ? "checkmark.circle.fill" : "square.and.arrow.down")
                            .font(.system(size: 24))
                            .foregroundColor(.white)
                            .frame(width: 44, height: 44)
                            .background(Circle().fill(Color.blue))
                    }
                    .disabled(isSaving || isLoading)
                }
                .padding()
                Spacer()

                // Joystick at bottom center
                SimpleJoystickOverlay()
            }
        }
        .background(Color.black)
        .navigationTitle("3D Room")
        .navigationBarTitleDisplayMode(.inline)
    }

    // MARK: - Save Room

    private func saveRoom() {
        isSaving = true

        // Copy PLY from temp to SavedRooms
        let fileManager = FileManager.default
        let documentsDirectory = fileManager.urls(for: .documentDirectory, in: .userDomainMask)[0]
        let savedRoomsDirectory = documentsDirectory.appendingPathComponent("SavedRooms", isDirectory: true)

        // Ensure SavedRooms directory exists
        do {
            try fileManager.createDirectory(at: savedRoomsDirectory, withIntermediateDirectories: true)
        } catch {
            logDebug("Failed to create SavedRooms directory: \(error)")
            isSaving = false
            return
        }

        // Copy PLY file to SavedRooms with same filename
        let destinationURL = savedRoomsDirectory.appendingPathComponent(plyURL.lastPathComponent)

        do {
            // Remove existing file if present
            if fileManager.fileExists(atPath: destinationURL.path) {
                try fileManager.removeItem(at: destinationURL)
            }
            try fileManager.copyItem(at: plyURL, to: destinationURL)
            logDebug("Saved room to: \(destinationURL.path)")

            // Notify model manager to refresh
            NotificationCenter.default.post(name: NSNotification.Name("RefreshSavedRooms"), object: nil)

            DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
                isSaving = false
            }
        } catch {
            logDebug("Failed to save room: \(error)")
            isSaving = false
        }
    }
}

// MARK: - MetalSplatter UIViewRepresentable

struct MetalSplatterViewRepresentable: UIViewControllerRepresentable {
    let plyURL: URL
    let onLoaded: (Int, Float, Float, Float, Float) -> Void  // count, width, height, depth, memoryMB
    let onError: (String) -> Void

    func makeUIViewController(context: Context) -> MetalSplatterViewController {
        let vc = MetalSplatterViewController()
        vc.plyURL = plyURL
        vc.onLoaded = onLoaded
        vc.onError = onError
        return vc
    }

    func updateUIViewController(_ uiViewController: MetalSplatterViewController, context: Context) {
        // No updates needed
    }
}

// MARK: - MetalSplatter View Controller

class MetalSplatterViewController: UIViewController, MTKViewDelegate {
    var plyURL: URL?
    var onLoaded: ((Int, Float, Float, Float, Float) -> Void)?  // count, width, height, depth, memoryMB
    var onError: ((String) -> Void)?

    private var mtkView: MTKView!
    private var device: MTLDevice!
    private var commandQueue: MTLCommandQueue!
    private var renderer: SplatRenderer?

    // Background fill (for areas with no splats)
    private var fillPipelineState: MTLRenderPipelineState?
    private var fillDepthState: MTLDepthStencilState?

    // Camera state
    private var cameraDistance: Float = 3.0
    private var cameraYaw: Float = 0.0
    private var cameraPitch: Float = 0.0
    private var cameraTarget: SIMD3<Float> = .zero
    private var cameraOffset: SIMD3<Float> = .zero  // Joystick-controlled offset
    private let moveSpeed: Float = 0.05
    private var initialCameraDistance: Float = 3.0


    override func viewDidLoad() {
        super.viewDidLoad()

        // Setup Metal device
        guard let device = MTLCreateSystemDefaultDevice() else {
            onError?("Metal is not supported on this device")
            return
        }
        self.device = device
        self.commandQueue = device.makeCommandQueue()

        // Setup Metal view
        mtkView = MTKView(frame: view.bounds, device: device)
        mtkView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        mtkView.colorPixelFormat = .bgra8Unorm
        mtkView.depthStencilPixelFormat = .depth32Float
        mtkView.clearColor = MTLClearColor(red: 0.85, green: 0.85, blue: 0.85, alpha: 1.0)  // Light gray to hide gaps
        mtkView.delegate = self
        view.addSubview(mtkView)

        // Setup gestures
        let panGesture = UIPanGestureRecognizer(target: self, action: #selector(handlePan(_:)))
        mtkView.addGestureRecognizer(panGesture)

        let pinchGesture = UIPinchGestureRecognizer(target: self, action: #selector(handlePinch(_:)))
        mtkView.addGestureRecognizer(pinchGesture)

        // Setup background fill pipeline
        setupFillPipeline()

        // Listen for recenter
        NotificationCenter.default.addObserver(self, selector: #selector(recenterCamera), name: NSNotification.Name("RecenterCamera"), object: nil)

        // Load PLY and setup renderer
        Task {
            await loadPLY()
        }
    }

    private func loadPLY() async {
        guard let url = plyURL else {
            await MainActor.run { onError?("No PLY file specified") }
            return
        }

        do {
            // Initialize MetalSplatter renderer with required parameters (sync, throws)
            renderer = try SplatRenderer(
                device: device,
                colorFormat: mtkView.colorPixelFormat,
                depthFormat: mtkView.depthStencilPixelFormat,
                sampleCount: mtkView.sampleCount,
                maxViewCount: 1,
                maxSimultaneousRenders: 3
            )

            // Set background to light gray immediately
            renderer?.clearColor = MTLClearColor(red: 0.7, green: 0.7, blue: 0.7, alpha: 1.0)

            // Load PLY file directly into the renderer (async)
            try await renderer?.read(from: url)

            // Get splat count and centroid from renderer
            let count = renderer?.splatCount ?? 0

            // Center camera on the splat centroid if available
            var width: Float = 0
            var height: Float = 0
            var depth: Float = 0

            if let centroid = renderer?.centroid {
                cameraTarget = centroid
            }
            if let bounds = renderer?.boundingBox {
                let size = bounds.max - bounds.min
                width = size.x
                height = size.y
                depth = size.z
                let maxDim = max(size.x, max(size.y, size.z))
                cameraDistance = maxDim * 0.7  // Closer camera to fill viewport
                initialCameraDistance = cameraDistance
            }

            // Calculate memory: PLY file size + GPU buffers (~56 bytes/splat for rendering)
            var memoryMB: Float = 0
            if let fileSize = try? FileManager.default.attributesOfItem(atPath: url.path)[.size] as? UInt64 {
                let gpuMemory = count * 56  // Approximate GPU buffer size per splat
                memoryMB = Float(fileSize + UInt64(gpuMemory)) / (1024 * 1024)
            }

            await MainActor.run {
                onLoaded?(count, width, height, depth, memoryMB)
            }

        } catch {
            await MainActor.run {
                onError?("Failed to load PLY: \(error.localizedDescription)")
            }
        }
    }

    // MARK: - Background Fill

    private func setupFillPipeline() {
        let shaderSource = """
        #include <metal_stdlib>
        using namespace metal;

        struct VertexOut {
            float4 position [[position]];
        };

        vertex VertexOut fillVertex(uint vid [[vertex_id]]) {
            float2 positions[3] = {
                float2(-1, -1),
                float2( 3, -1),
                float2(-1,  3)
            };
            VertexOut out;
            out.position = float4(positions[vid], 0.00001, 1.0);  // Just above far plane (reverse-Z: far=0)
            return out;
        }

        fragment float4 fillFragment() {
            return float4(0.7, 0.7, 0.7, 1.0);  // Light gray
        }
        """

        do {
            let library = try device.makeLibrary(source: shaderSource, options: nil)
            let pipelineDesc = MTLRenderPipelineDescriptor()
            pipelineDesc.vertexFunction = library.makeFunction(name: "fillVertex")
            pipelineDesc.fragmentFunction = library.makeFunction(name: "fillFragment")
            pipelineDesc.colorAttachments[0].pixelFormat = mtkView.colorPixelFormat
            pipelineDesc.depthAttachmentPixelFormat = mtkView.depthStencilPixelFormat
            fillPipelineState = try device.makeRenderPipelineState(descriptor: pipelineDesc)

            // Reverse-Z: splats have depth > 0, empty areas have depth = 0
            // Fill where depth <= 0.00001 (empty far plane areas)
            let depthDesc = MTLDepthStencilDescriptor()
            depthDesc.depthCompareFunction = .greater  // Pass if new > existing (0.00001 > 0.0)
            depthDesc.isDepthWriteEnabled = false
            fillDepthState = device.makeDepthStencilState(descriptor: depthDesc)
        } catch {
            print("Fill pipeline error: \(error)")
        }
    }

    private func renderFill(commandBuffer: MTLCommandBuffer, drawable: CAMetalDrawable, depthTexture: MTLTexture?) {
        guard let pipeline = fillPipelineState,
              let depthState = fillDepthState,
              let depthTex = depthTexture else { return }

        let passDesc = MTLRenderPassDescriptor()
        passDesc.colorAttachments[0].texture = drawable.texture
        passDesc.colorAttachments[0].loadAction = .load
        passDesc.colorAttachments[0].storeAction = .store
        passDesc.depthAttachment.texture = depthTex
        passDesc.depthAttachment.loadAction = .load
        passDesc.depthAttachment.storeAction = .dontCare

        guard let encoder = commandBuffer.makeRenderCommandEncoder(descriptor: passDesc) else { return }
        encoder.setRenderPipelineState(pipeline)
        encoder.setDepthStencilState(depthState)
        encoder.drawPrimitives(type: .triangle, vertexStart: 0, vertexCount: 3)
        encoder.endEncoding()
    }

    // MARK: - MTKViewDelegate

    func mtkView(_ view: MTKView, drawableSizeWillChange size: CGSize) {
        // Handle size change if needed
    }

    func draw(in view: MTKView) {
        guard let renderer = renderer,
              let drawable = view.currentDrawable,
              let commandBuffer = commandQueue.makeCommandBuffer() else {
            return
        }

        let drawableSize = view.drawableSize

        // Process joystick input for camera movement
        let joystickOffset = GlobalCameraController.shared.joystickOffset
        if joystickOffset.width != 0 || joystickOffset.height != 0 {
            let jx = Float(joystickOffset.width) / 30.0
            let jy = Float(joystickOffset.height) / 30.0

            // Calculate movement in camera-relative directions
            let forward = SIMD3<Float>(sin(cameraYaw), 0, cos(cameraYaw))
            let right = SIMD3<Float>(cos(cameraYaw), 0, -sin(cameraYaw))

            cameraOffset += forward * (-jy * moveSpeed) + right * (jx * moveSpeed)
        }

        // Build view matrix from camera state
        let cameraPosition = calculateCameraPosition()
        let adjustedTarget = cameraTarget + cameraOffset  // Move target with camera
        let viewMatrix = makeLookAtMatrix(eye: cameraPosition, target: adjustedTarget, up: SIMD3<Float>(0, 1, 0))

        // Build projection matrix
        let aspect = Float(drawableSize.width / drawableSize.height)
        let fovy: Float = Float.pi / 4.0  // 45 degrees
        let projectionMatrix = makePerspectiveMatrix(fovy: fovy, aspect: aspect, near: 0.1, far: 100.0)

        // Create MTLViewport
        let mtlViewport = MTLViewport(
            originX: 0,
            originY: 0,
            width: drawableSize.width,
            height: drawableSize.height,
            znear: 0.0,
            zfar: 1.0
        )

        // Create viewport descriptor
        let viewport = SplatRenderer.ViewportDescriptor(
            viewport: mtlViewport,
            projectionMatrix: projectionMatrix,
            viewMatrix: viewMatrix,
            screenSize: SIMD2<Int>(Int(drawableSize.width), Int(drawableSize.height))
        )

        do {
            try renderer.render(
                viewports: [viewport],
                colorTexture: view.multisampleColorTexture ?? drawable.texture,
                colorStoreAction: view.multisampleColorTexture == nil ? .store : .multisampleResolve,
                depthTexture: view.depthStencilTexture,
                rasterizationRateMap: nil,
                renderTargetArrayLength: 0,
                to: commandBuffer
            )
        } catch {
            print("Render error: \(error)")
        }

        // Fill gray where no splats (reverse-Z depth test)
        renderFill(commandBuffer: commandBuffer, drawable: drawable, depthTexture: view.depthStencilTexture)

        commandBuffer.present(drawable)
        commandBuffer.commit()
    }

    // MARK: - Gesture Handlers

    @objc private func handlePan(_ gesture: UIPanGestureRecognizer) {
        let translation = gesture.translation(in: gesture.view)
        let sensitivity: Float = 0.01

        cameraYaw += Float(translation.x) * sensitivity
        cameraPitch -= Float(translation.y) * sensitivity

        // Limit rotation to avoid viewing angles with artifacts
        let maxYaw: Float = .pi * 0.25      // ±45 degrees horizontal
        let maxPitch: Float = .pi * 0.20    // ±36 degrees vertical
        cameraYaw = max(-maxYaw, min(maxYaw, cameraYaw))
        cameraPitch = max(-maxPitch, min(maxPitch, cameraPitch))

        gesture.setTranslation(.zero, in: gesture.view)
    }

    @objc private func handlePinch(_ gesture: UIPinchGestureRecognizer) {
        if gesture.state == .changed {
            let delta = Float(1.0 - gesture.scale)
            cameraDistance *= (1.0 + delta * 0.5)
            cameraDistance = max(0.5, min(20.0, cameraDistance))
            gesture.scale = 1.0
        }
    }

    @objc private func recenterCamera() {
        cameraYaw = 0
        cameraPitch = 0
        cameraOffset = .zero
        cameraDistance = initialCameraDistance
    }

    // MARK: - Camera Math

    private func calculateCameraPosition() -> SIMD3<Float> {
        let baseX = cameraTarget.x + cameraDistance * cos(cameraPitch) * sin(cameraYaw)
        let baseY = cameraTarget.y + cameraDistance * sin(cameraPitch)
        let baseZ = cameraTarget.z + cameraDistance * cos(cameraPitch) * cos(cameraYaw)
        // Add joystick-controlled offset
        return SIMD3<Float>(baseX + cameraOffset.x, baseY, baseZ + cameraOffset.z)
    }

    private func makeLookAtMatrix(eye: SIMD3<Float>, target: SIMD3<Float>, up: SIMD3<Float>) -> simd_float4x4 {
        let zAxis = normalize(eye - target)
        let xAxis = normalize(cross(up, zAxis))
        let yAxis = cross(zAxis, xAxis)

        return simd_float4x4(columns: (
            SIMD4<Float>(xAxis.x, yAxis.x, zAxis.x, 0),
            SIMD4<Float>(xAxis.y, yAxis.y, zAxis.y, 0),
            SIMD4<Float>(xAxis.z, yAxis.z, zAxis.z, 0),
            SIMD4<Float>(-dot(xAxis, eye), -dot(yAxis, eye), -dot(zAxis, eye), 1)
        ))
    }

    private func makePerspectiveMatrix(fovy: Float, aspect: Float, near: Float, far: Float) -> simd_float4x4 {
        let yScale = 1 / tan(fovy * 0.5)
        let xScale = yScale / aspect
        let zRange = far - near
        let zScale = -(far + near) / zRange
        let wzScale = -2 * far * near / zRange

        return simd_float4x4(columns: (
            SIMD4<Float>(xScale, 0, 0, 0),
            SIMD4<Float>(0, yScale, 0, 0),
            SIMD4<Float>(0, 0, zScale, -1),
            SIMD4<Float>(0, 0, wzScale, 0)
        ))
    }
}

// MARK: - Preview

#Preview {
    NavigationStack {
        // Preview with a sample URL (won't actually load)
        SharpRoomView(plyURL: URL(fileURLWithPath: "/sample.ply"))
    }
}
