import SwiftUI
import MetalKit

// Note: Add MetalSplatter package via Xcode:
// File > Add Package Dependencies > https://github.com/scier/MetalSplatter.git
import MetalSplatter

/// Simple 3D Gaussian Splat viewer using MetalSplatter
/// Renders PLY files generated by SHARP without any room-aware processing
struct SharpRoomView: View {
    let plyURL: URL

    @State private var isLoading = true
    @State private var error: String?
    @State private var splatCount: Int = 0
    @State private var roomWidth: Float = 0
    @State private var roomHeight: Float = 0
    @State private var roomDepth: Float = 0

    var body: some View {
        ZStack {
            // MetalSplatter view
            MetalSplatterViewRepresentable(
                plyURL: plyURL,
                onLoaded: { count, width, height, depth in
                    splatCount = count
                    roomWidth = width
                    roomHeight = height
                    roomDepth = depth
                    isLoading = false
                },
                onError: { err in
                    error = err
                    isLoading = false
                }
            )
            .ignoresSafeArea()

            // Loading overlay
            if isLoading {
                VStack(spacing: 16) {
                    ProgressView()
                        .scaleEffect(1.5)
                    Text("Loading splats...")
                        .foregroundColor(.white)
                }
                .padding(24)
                .background(Color.black.opacity(0.7))
                .cornerRadius(12)
            }

            // Error overlay
            if let error = error {
                VStack(spacing: 16) {
                    Image(systemName: "exclamationmark.triangle")
                        .font(.largeTitle)
                        .foregroundColor(.orange)
                    Text(error)
                        .foregroundColor(.white)
                        .multilineTextAlignment(.center)
                }
                .padding(24)
                .background(Color.black.opacity(0.7))
                .cornerRadius(12)
            }

            // HUD
            VStack {
                HStack {
                    if splatCount > 0 {
                        VStack(alignment: .leading, spacing: 2) {
                            Text("W: \(String(format: "%.1f", roomWidth))  H: \(String(format: "%.1f", roomHeight))  D: \(String(format: "%.1f", roomDepth))")
                                .font(.caption.monospacedDigit())
                                .foregroundColor(.white)
                        }
                        .padding(8)
                        .background(Color.black.opacity(0.5))
                        .cornerRadius(8)
                    }
                    Spacer()
                }
                .padding()
                Spacer()

                // Controls hint
                HStack {
                    Image(systemName: "hand.draw")
                    Text("Drag to rotate, Pinch to zoom")
                        .font(.caption)
                }
                .foregroundColor(.white)
                .padding(8)
                .background(Color.black.opacity(0.5))
                .cornerRadius(8)
                .padding()
            }
        }
        .background(Color.black)
        .navigationTitle("3D Room")
        .navigationBarTitleDisplayMode(.inline)
    }
}

// MARK: - MetalSplatter UIViewRepresentable

struct MetalSplatterViewRepresentable: UIViewControllerRepresentable {
    let plyURL: URL
    let onLoaded: (Int, Float, Float, Float) -> Void  // count, width, height, depth
    let onError: (String) -> Void

    func makeUIViewController(context: Context) -> MetalSplatterViewController {
        let vc = MetalSplatterViewController()
        vc.plyURL = plyURL
        vc.onLoaded = onLoaded
        vc.onError = onError
        return vc
    }

    func updateUIViewController(_ uiViewController: MetalSplatterViewController, context: Context) {
        // No updates needed
    }
}

// MARK: - MetalSplatter View Controller

class MetalSplatterViewController: UIViewController, MTKViewDelegate {
    var plyURL: URL?
    var onLoaded: ((Int, Float, Float, Float) -> Void)?  // count, width, height, depth
    var onError: ((String) -> Void)?

    private var mtkView: MTKView!
    private var device: MTLDevice!
    private var commandQueue: MTLCommandQueue!
    private var renderer: SplatRenderer?

    // Camera state
    private var cameraDistance: Float = 3.0
    private var cameraYaw: Float = 0.0
    private var cameraPitch: Float = 0.0
    private var cameraTarget: SIMD3<Float> = .zero

    override func viewDidLoad() {
        super.viewDidLoad()

        // Setup Metal device
        guard let device = MTLCreateSystemDefaultDevice() else {
            onError?("Metal is not supported on this device")
            return
        }
        self.device = device
        self.commandQueue = device.makeCommandQueue()

        // Setup Metal view
        mtkView = MTKView(frame: view.bounds, device: device)
        mtkView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        mtkView.colorPixelFormat = .bgra8Unorm
        mtkView.depthStencilPixelFormat = .depth32Float
        mtkView.clearColor = MTLClearColor(red: 0.1, green: 0.1, blue: 0.12, alpha: 1.0)
        mtkView.delegate = self
        view.addSubview(mtkView)

        // Setup gestures
        let panGesture = UIPanGestureRecognizer(target: self, action: #selector(handlePan(_:)))
        mtkView.addGestureRecognizer(panGesture)

        let pinchGesture = UIPinchGestureRecognizer(target: self, action: #selector(handlePinch(_:)))
        mtkView.addGestureRecognizer(pinchGesture)

        // Load PLY and setup renderer
        Task {
            await loadPLY()
        }
    }

    private func loadPLY() async {
        guard let url = plyURL else {
            await MainActor.run { onError?("No PLY file specified") }
            return
        }

        do {
            // Initialize MetalSplatter renderer with required parameters (sync, throws)
            renderer = try SplatRenderer(
                device: device,
                colorFormat: mtkView.colorPixelFormat,
                depthFormat: mtkView.depthStencilPixelFormat,
                sampleCount: mtkView.sampleCount,
                maxViewCount: 1,
                maxSimultaneousRenders: 3
            )

            // Load PLY file directly into the renderer (async)
            try await renderer?.read(from: url)

            // Get splat count and centroid from renderer
            let count = renderer?.splatCount ?? 0

            // Center camera on the splat centroid if available
            var width: Float = 0
            var height: Float = 0
            var depth: Float = 0

            if let centroid = renderer?.centroid {
                cameraTarget = centroid
            }
            if let bounds = renderer?.boundingBox {
                let size = bounds.max - bounds.min
                width = size.x
                height = size.y
                depth = size.z
                let maxDim = max(size.x, max(size.y, size.z))
                cameraDistance = maxDim * 0.7  // Closer camera to fill viewport
            }

            await MainActor.run {
                onLoaded?(count, width, height, depth)
            }

        } catch {
            await MainActor.run {
                onError?("Failed to load PLY: \(error.localizedDescription)")
            }
        }
    }

    // MARK: - MTKViewDelegate

    func mtkView(_ view: MTKView, drawableSizeWillChange size: CGSize) {
        // Handle size change if needed
    }

    func draw(in view: MTKView) {
        guard let renderer = renderer,
              let drawable = view.currentDrawable,
              let commandBuffer = commandQueue.makeCommandBuffer() else {
            return
        }

        let drawableSize = view.drawableSize

        // Build view matrix from camera state
        let cameraPosition = calculateCameraPosition()
        let viewMatrix = makeLookAtMatrix(eye: cameraPosition, target: cameraTarget, up: SIMD3<Float>(0, 1, 0))

        // Build projection matrix
        let aspect = Float(drawableSize.width / drawableSize.height)
        let fovy: Float = Float.pi / 4.0  // 45 degrees
        let projectionMatrix = makePerspectiveMatrix(fovy: fovy, aspect: aspect, near: 0.1, far: 100.0)

        // Create MTLViewport
        let mtlViewport = MTLViewport(
            originX: 0,
            originY: 0,
            width: drawableSize.width,
            height: drawableSize.height,
            znear: 0.0,
            zfar: 1.0
        )

        // Create viewport descriptor
        let viewport = SplatRenderer.ViewportDescriptor(
            viewport: mtlViewport,
            projectionMatrix: projectionMatrix,
            viewMatrix: viewMatrix,
            screenSize: SIMD2<Int>(Int(drawableSize.width), Int(drawableSize.height))
        )

        do {
            try renderer.render(
                viewports: [viewport],
                colorTexture: view.multisampleColorTexture ?? drawable.texture,
                colorStoreAction: view.multisampleColorTexture == nil ? .store : .multisampleResolve,
                depthTexture: view.depthStencilTexture,
                rasterizationRateMap: nil,
                renderTargetArrayLength: 0,
                to: commandBuffer
            )
        } catch {
            print("Render error: \(error)")
        }

        commandBuffer.present(drawable)
        commandBuffer.commit()
    }

    // MARK: - Gesture Handlers

    @objc private func handlePan(_ gesture: UIPanGestureRecognizer) {
        let translation = gesture.translation(in: gesture.view)
        let sensitivity: Float = 0.01

        cameraYaw += Float(translation.x) * sensitivity
        cameraPitch -= Float(translation.y) * sensitivity
        cameraPitch = max(-Float.pi * 0.45, min(Float.pi * 0.45, cameraPitch))

        gesture.setTranslation(.zero, in: gesture.view)
    }

    @objc private func handlePinch(_ gesture: UIPinchGestureRecognizer) {
        if gesture.state == .changed {
            let delta = Float(1.0 - gesture.scale)
            cameraDistance *= (1.0 + delta * 0.5)
            cameraDistance = max(0.5, min(20.0, cameraDistance))
            gesture.scale = 1.0
        }
    }

    // MARK: - Camera Math

    private func calculateCameraPosition() -> SIMD3<Float> {
        let x = cameraTarget.x + cameraDistance * cos(cameraPitch) * sin(cameraYaw)
        let y = cameraTarget.y + cameraDistance * sin(cameraPitch)
        let z = cameraTarget.z + cameraDistance * cos(cameraPitch) * cos(cameraYaw)
        return SIMD3<Float>(x, y, z)
    }

    private func makeLookAtMatrix(eye: SIMD3<Float>, target: SIMD3<Float>, up: SIMD3<Float>) -> simd_float4x4 {
        let zAxis = normalize(eye - target)
        let xAxis = normalize(cross(up, zAxis))
        let yAxis = cross(zAxis, xAxis)

        return simd_float4x4(columns: (
            SIMD4<Float>(xAxis.x, yAxis.x, zAxis.x, 0),
            SIMD4<Float>(xAxis.y, yAxis.y, zAxis.y, 0),
            SIMD4<Float>(xAxis.z, yAxis.z, zAxis.z, 0),
            SIMD4<Float>(-dot(xAxis, eye), -dot(yAxis, eye), -dot(zAxis, eye), 1)
        ))
    }

    private func makePerspectiveMatrix(fovy: Float, aspect: Float, near: Float, far: Float) -> simd_float4x4 {
        let yScale = 1 / tan(fovy * 0.5)
        let xScale = yScale / aspect
        let zRange = far - near
        let zScale = -(far + near) / zRange
        let wzScale = -2 * far * near / zRange

        return simd_float4x4(columns: (
            SIMD4<Float>(xScale, 0, 0, 0),
            SIMD4<Float>(0, yScale, 0, 0),
            SIMD4<Float>(0, 0, zScale, -1),
            SIMD4<Float>(0, 0, wzScale, 0)
        ))
    }
}

// MARK: - Preview

#Preview {
    NavigationStack {
        // Preview with a sample URL (won't actually load)
        SharpRoomView(plyURL: URL(fileURLWithPath: "/sample.ply"))
    }
}
